# Generated by Django 3.1.2 on 2021-04-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusdetail',
            name='status',
            field=models.CharField(choices=[('Replied', 'Replied'), ('Resolved', 'Resolved'), ('Pending', 'Pending'), ('Spam', 'Spam')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='contactusdetail',
            name='typeOfMessage',
            field=models.CharField(choices=[('Grievance', 'Grievance'), ('Feedback', 'Feedback')], max_length=10),
        ),
    ]
