# Generated by Django 3.1.2 on 2021-04-21 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210420_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userdetail'),
        ),
        migrations.AlterField(
            model_name='labcoat',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userdetail'),
        ),
    ]
