# Generated by Django 3.1.2 on 2021-04-24 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210422_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Refurbished/Books/')),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.book')),
            ],
        ),
    ]
