# Generated by Django 3.1.1 on 2020-10-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_userdetail_academicdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrefurbished',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='productrefurbished',
            name='seller',
            field=models.CharField(max_length=50),
        ),
    ]
