# Generated by Django 3.1.2 on 2021-04-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_bookimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabcoatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Refurbished/Labcoats/')),
                ('labcoat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.labcoat')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Refurbished/Instruments/')),
                ('instrument', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.instrument')),
            ],
        ),
    ]
