# Generated by Django 3.2.3 on 2021-05-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='priduct',
            new_name='product',
        ),
    ]
