# Generated by Django 3.2.3 on 2021-05-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_priduct_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_calculator',
            field=models.BooleanField(default=False),
        ),
    ]
