# Generated by Django 3.1.1 on 2020-10-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201028_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrefurbished',
            name='sellerID',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
