# Generated by Django 3.1.1 on 2020-10-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201028_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrefurbished',
            name='sellerID',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productrefurbished',
            name='seller',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
