# Generated by Django 3.1.2 on 2020-10-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201013_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('typeOfMessage', models.CharField(choices=[('1', 'Grievance'), ('2', 'Feedback')], max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
