# Generated by Django 3.1.2 on 2020-10-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contactusdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUsDetails',
            new_name='ContactUsDetail',
        ),
    ]
