# Generated by Django 3.1.2 on 2020-10-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201014_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='academicDetails',
        ),
    ]
