# Generated by Django 3.1.1 on 2020-10-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201023_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrefurbished',
            name='seller',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
