# Generated by Django 3.1.1 on 2020-10-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201023_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrefurbished',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
