# Generated by Django 3.1.1 on 2020-10-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201025_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTotal',
            field=models.FloatField(null=True),
        ),
    ]
