# Generated by Django 3.1.2 on 2020-11-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_placed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productnew',
            options={'verbose_name_plural': 'New Products'},
        ),
        migrations.AlterModelOptions(
            name='productrefurbished',
            options={'verbose_name_plural': 'Refurbished Products'},
        ),
        migrations.AlterField(
            model_name='productnew',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
